version: '3'

services:
  spring2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9999:9999
    depends_on:
      - db

  db:
    image: postgres:alpine
    ports:
      - 15432:5432
    container_name: server_database

networks:
  datalink:
    driver: bridge