version: '3'

services:
  spring2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9999:9999
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 15432:5432
    container_name: server_database
    environment:
      - POSTGRES_USER=string
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=str

networks:
  datalink:
    driver: bridge